# Generated by Django 4.2.13 on 2026-04-13 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("sleep", models.FloatField()),
                (
                    "stress",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "exercise",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("light", "Light"),
                            ("moderate", "Moderate"),
                            ("intense", "Intense"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "medication",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=5,
                    ),
                ),
                ("medication_details", models.TextField(blank=True, null=True)),
                (
                    "food",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("junk", "Junk"),
                            ("mixed", "Mixed"),
                        ],
                        default="mixed",
                        max_length=10,
                    ),
                ),
                (
                    "routine_change",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=5,
                    ),
                ),
                ("routine_details", models.TextField(blank=True, null=True)),
                (
                    "white_discharge",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("light", "Light"),
                            ("medium", "Medium"),
                            ("heavy", "Heavy"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "hydration",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="yes",
                        max_length=5,
                    ),
                ),
                ("symptoms", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="CycleLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("pain", models.IntegerField()),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "flow",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("medium", "Medium"),
                            ("heavy", "Heavy"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sleep", models.FloatField()),
                (
                    "stress",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "exercise",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("light", "Light"),
                            ("moderate", "Moderate"),
                            ("intense", "Intense"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "medication",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=5,
                    ),
                ),
                ("medication_details", models.TextField(blank=True, null=True)),
                (
                    "hydration",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="yes",
                        max_length=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycle_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
