# Generated by Django 4.2.13 on 2026-04-09 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("log_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailylog",
            name="flow",
        ),
        migrations.RemoveField(
            model_name="dailylog",
            name="mood",
        ),
        migrations.RemoveField(
            model_name="dailylog",
            name="pain",
        ),
        migrations.AddField(
            model_name="dailylog",
            name="food",
            field=models.CharField(
                choices=[("healthy", "Healthy"), ("junk", "Junk"), ("mixed", "Mixed")],
                default="mixed",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="hydration",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="yes", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="medication",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="medication_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="routine_change",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="routine_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="symptoms",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="white_discharge",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("light", "Light"),
                    ("medium", "Medium"),
                    ("heavy", "Heavy"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="CycleLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("pain", models.IntegerField()),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "flow",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("medium", "Medium"),
                            ("heavy", "Heavy"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sleep", models.FloatField()),
                (
                    "stress",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "exercise",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("light", "Light"),
                            ("moderate", "Moderate"),
                            ("intense", "Intense"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "medication",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=5,
                    ),
                ),
                ("medication_details", models.TextField(blank=True, null=True)),
                (
                    "hydration",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="yes",
                        max_length=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycle_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
