# Generated by Django 4.2.13 on 2026-04-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_app", "0002_remove_dailylog_flow_remove_dailylog_mood_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cyclelog",
            name="stress",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                ],
                max_length=10,
            ),
        ),
    ]
