# Generated by Django 4.2.13 on 2026-04-09 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MyHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "q1",
                    models.CharField(
                        choices=[
                            ("Regular", "Regular"),
                            ("Occasionally missed", "Occasionally missed"),
                            ("Persistent/recurrent", "Persistent/recurrent"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "q2",
                    models.CharField(
                        choices=[
                            ("Light", "Light"),
                            ("Moderate", "Moderate"),
                            ("Heavy", "Heavy"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "q3",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Noticeable", "Noticeable"),
                            ("Significant", "Significant"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "q4",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Mild (1-4 kg)", "Mild (1-4 kg)"),
                            ("Moderate (5-8 kg)", "Moderate (5-8 kg)"),
                            ("Severe (9+ kg)", "Severe (9+ kg)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "q5",
                    models.CharField(
                        choices=[
                            ("No", "No"),
                            ("Mild", "Mild"),
                            ("Moderate", "Moderate"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "q6",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=50
                    ),
                ),
                (
                    "q7",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Mild", "Mild"),
                            ("Significant", "Significant"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "q8",
                    models.CharField(
                        choices=[
                            ("Normal energy", "Normal energy"),
                            ("Mild fatigue", "Mild fatigue"),
                            ("Strong fatigue/crashes", "Strong fatigue/crashes"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "q9",
                    models.CharField(
                        choices=[
                            ("Never", "Never"),
                            ("1 time/week", "1 time/week"),
                            ("2-3 times/week", "2-3 times/week"),
                            ("Daily", "Daily"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "q10",
                    models.CharField(
                        choices=[
                            ("Healthy", "Healthy"),
                            ("Mixed", "Mixed"),
                            ("Junk", "Junk"),
                        ],
                        max_length=50,
                    ),
                ),
                ("score", models.IntegerField(blank=True, null=True)),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Low", "Low"),
                            ("Moderate", "Moderate"),
                            ("High", "High"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_health",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
