# Generated by Django 4.2.13 on 2026-04-13 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MyHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("q1", models.CharField(max_length=100)),
                ("q2", models.CharField(max_length=100)),
                ("q3", models.CharField(max_length=100)),
                ("q4", models.CharField(max_length=100)),
                ("q5", models.CharField(max_length=100)),
                ("q6", models.CharField(max_length=100)),
                ("q7", models.CharField(max_length=100)),
                ("q8", models.CharField(max_length=100)),
                ("q9", models.CharField(max_length=100)),
                ("q10", models.CharField(max_length=100)),
                ("score", models.IntegerField(blank=True, null=True)),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Low", "Low"),
                            ("Moderate", "Moderate"),
                            ("High", "High"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_health",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
