# Generated by Django 4.2.13 on 2026-04-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myhealth",
            name="q1",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="myhealth",
            name="q10",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="myhealth",
            name="q2",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="myhealth",
            name="q3",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="myhealth",
            name="q4",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="myhealth",
            name="q5",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="myhealth",
            name="q6",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="myhealth",
            name="q7",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="myhealth",
            name="q8",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="myhealth",
            name="q9",
            field=models.CharField(max_length=100),
        ),
    ]
